title: Royale
description: My Blog
theme: just-the-docs
domain: commandity.github.io
url: https://commandity.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
